### ISSUE TITLE
PostgreSQL 12 ERROR:  column "relhasoids" does not exist

### ISSUE THREAD

**Issue by denisorlov** [dockage/phppgadmin#2] opened 2019-12-25 13:12 UTC
PostgreSQL 12.1

```
Error SQL:

ERROR:  column "relhasoids" does not exist
LINE 1: SELECT relhasoids FROM pg_catalog.pg_class WHERE relname='us...
               ^
In operator:

SELECT relhasoids FROM pg_catalog.pg_class WHERE relname='user'
			AND relnamespace = (SELECT oid FROM pg_catalog.pg_namespace WHERE nspname='usersm')

```
**cause**:
https://stackoverflow.com/questions/58461178/how-to-fix-error-column-c-relhasoids-does-not-exist-in-postgres

**solution commited**:
https://github.com/phppgadmin/phppgadmin/pull/81/commits/418b7e1a4433fc71bd202604e9fd389f2acd1510

Can you fix it please?

**Comment by wapmorgan** [comment] 2020-05-12 17:41
Should be fixed with new PhpPgAdmin (#4)

**Comment by atkrad** [comment] 2020-05-19 06:10
@denisorlov @wapmorgan Please see my comment: https://github.com/dockage/phppgadmin/pull/4#issuecomment-630602949

**Closed** 2020-05-19 06:10 UTC

**Comment by mainangethe** [comment] 2021-04-19 02:48
A simpler explanation for future Googlers. 
## TLD
This occurs when you're most likely reviewing a table made from v12+ but reviewing it in a psql/ Postgres client that is below that version (v11-).
Solution is to ensure your client is at least 12+.

## Root Cause
OIDs column types are no longer special columns in v12+, hence the break
[Reference Site](https://postgresql.verite.pro/blog/2019/04/24/oid-column.html)
